name: imul
description: Performs C-like 32-bit integer multiplication
version: 0.1.0
homepage: https://github.com/smuthsoft/imul

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  benchmark_harness: ^2.0.0
  lints: ^1.0.0
  test: ^1.21.0
